#! /usr/bin/env python

"""
    simple google dictionary in python
"""
from __future__ import print_function
from __future__ import unicode_literals
import sys
import os
from argparse import ArgumentParser, SUPPRESS
import re
from textwrap import fill
from urllib2 import urlopen, URLError
from ast import literal_eval
reload(sys)
#sys.setdefaultencoding('utf8')

_COLOR = {
    # refrence  : http       : //en.wikipedia.org/wiki/ANSI_escape_code
    'bold'      : "\033[1m",
    'underline' : "\033[4m",
    'blink'     : "\033[5m",
    'reverse'   : "\033[7m",
    'concealed' : "\033[8m",

    'black'     : "\033[30m",
    'red'       : "\033[31m",
    'green'     : "\033[32m",
    'yellow'    : "\033[33m",
    'blue'      : "\033[34m",
    'magenta'   : "\033[35m",
    'cyan'      : "\033[36m",
    'white'     : "\033[37m",
    'd_black'   : "\033[30;2m",
    'd_red'     : "\033[31;2m",
    'd_green'   : "\033[32;2m",
    'd_yellow'  : "\033[33;2m",
    'd_blue'    : "\033[34;2m",
    'd_magenta' : "\033[35;2m",
    'd_cyan'    : "\033[36;2m",
    'd_white'   : "\033[37;2m",
    'b_cyan'      : "\033[36;1m",
    'b_green'     : "\033[32;1m",

    'on_black'   : "\033[40m",
    'on_red'     : "\033[41m",
    'on_green'   : "\033[42m",
    'on_yellow'  : "\033[43m",
    'on_blue'    : "\033[44m",
    'on_magenta' : "\033[45m",
    'on_cyan'    : "\033[46m",
    'on_white'   : "\033[47m",

    'beep': "\007",
}

TERM_FORMAT = {
    'none'     : "",
    'close'    : "\033[0m",
    'headword' : _COLOR['b_cyan'],
    'label' : _COLOR['bold'],
    'related'  : _COLOR['d_white'],
    'meaning'  : _COLOR['yellow'],
    'highlight'  : _COLOR['underline'],
    'synonym'  : _COLOR['blue'],
    'item': _COLOR['b_green'],
    'index': _COLOR['red']
}

class Fmt(object):
    """quick way for format"""
    def __init__(self, **opts):
        """options for format"""
        super(Fmt, self).__init__()
        self.options = opts

    def __getattr__(self, color):
        opts = self.options
        if opts.get('no-fmt') or color not in TERM_FORMAT:
            return lambda text: text
        if not opts.get(color, 1):
            return lambda text: text

        return lambda text:\
                '%s%s%s'% (TERM_FORMAT[color], text, TERM_FORMAT['close'])

    _invisible = re.compile(r'\033\[\d+(;\d+)?m')
    @classmethod
    def unprint_cnt(cls, text):
        """get count of printable"""
        printable = cls._invisible.sub('', text)
        return len(text) - len(printable)

    @staticmethod
    def wrap_list(lst, indent=4):
        """break long word for related"""
        index = len(lst) - 1
        index -= index % 2
        while index:
            lst[index] = '\n' + ' '*indent + lst[index]
            index -= 2

    def show(self, ent_type):
        """whether entry type is not visible"""
        return self.options.get(ent_type, 1)

FMT = Fmt()

def print_def(word):
    """format definition of word
    """
    if not word:
        return
    definition = get_def(word)
    definition = format_output(definition)
    print("Definition for %s:\n %s" % (word, definition))


def get_def(word):
    """get definition from google dictionary api
    """
    goo_dict = 'http://www.google.com/dictionary/json'
    goo_dict += '?callback=s&q={query}&sl=en&tl=en&restrict=pr,de,sy&client=te'
    url = goo_dict.format(query=word)
    definition = ''
    try:
        def_source = urlopen(url)
        definition = def_source.read()[2:-10]
    except URLError as err:
        print('Error in open url')
        print(err)
    finally:
        #explicitly close it
        def_source.close()

    # strip unused token
    # RE is slow
    return literal_eval(definition)


def terms(term_list, ent_type):
    """terms(term_list, ent_type) -> string
    convert terms into beautiful string
    """
    ret = []
    separator = ''

    if ent_type == 'meaning':
        separator = '\n'
        for term in term_list:
            text = term['text']
            text = re.sub(r'<em>(.*?)</em>', '\1', text)
            text = re.sub(r'<i>(.*?)</i>', '\1', text)
            text = fill(text, subsequent_indent=' '*7)
            ret.append(FMT.meaning(text))

    elif ent_type == 'related':
        separator = ', '
        for term in term_list:
            label = term.get('labels', [{}])[0]
            label = label.get('text', '')
            text = '%s %s'% (term['text'], FMT.related(label))
            ret.append(text)
        ret[0] = '    ' + ret[0]
        FMT.wrap_list(ret)

    elif ent_type == 'example':
        separator = '\n'
        repl = lambda t: FMT.highlight(t.group(1))
        for term in term_list:
            text = term['text']
            text = re.sub(r'<em>(.*?)</em>', repl, text)
            text = re.sub(r'<b>(.*?)</b>', '\1', text)
            text = ' '*8 + '%s %s' % (FMT.item('*'), text)
            width = 70 + FMT.unprint_cnt(text)
            # add max width for escaped width
            text = fill(text, width = width, \
                    subsequent_indent=' '*10)
            ret.append(text)

    elif ent_type == 'headword':
        word = term_list[0]
        text = '\n\n  ' + FMT.headword(word['text'])
        ret.append(text)
        if 'labels' in word:
            label = word['labels'][0]['text']
            ret.append(' '+FMT.label(label))
        term_list = term_list[1:]
        separator = ' | '
        ret.extend([term['text'] for term in term_list\
                if term['type'] != 'sound'])

    elif ent_type == 'synonym':
        separator = ', '
        ret = [term['text'] for term in term_list]
        ret[0] = '  ' + ret[0]

    return separator.join(ret)


def entry(ent, index=0):
    """entry(ent, index=0) -> string
    ent is a dict has 3 keys:
        'type': string
        'terms': <term_list>
            term:
                type: string
                text: string
                language: string
                [labels]: <dict>
        'entries': <entry_list>
    """
    ent_type = ent.get('type', '')
    ret = []
    term_list = ent.get('terms', [])
    term_text = None

    if FMT.show(ent_type):
        term_text = terms(term_list, ent_type)

    if ent_type == 'meaning':
        term_text = '    {0}: {1}'.format(\
                FMT.index(str(index)),  term_text)
    elif ent_type == 'synonym' and FMT.show('synonym'):
        label = ent['labels'][0]['text']
        ret.append('  '+FMT.synonym(label+': '))

    if term_text is not None:
        ret.append(term_text)
    entries = ent.get('entries', [])
    for num, child in enumerate(entries):
        if ent_type == 'synonyms':
            child['type'] = 'synonym'
        ret.append(entry(child, num))
    return '\n'.join(ret)



def format_output(dfn):
    """format_output(definition) -> string
    """
    ret = []
    if 'synonyms' in dfn:
        for ent in dfn['synonyms']:
            ent['type'] = 'synonyms'
            ret.append(entry(ent))
    if 'primaries' in dfn:
        ret.extend([entry(ent) for ent in dfn['primaries']])

    return ''.join(ret)

def main():
    '''pylint hurts'''
    parser = ArgumentParser(description='Google Dictionary in Console.')
    parser.add_argument('-f', '--full',
                        action='store_true', default=False)
    parser.add_argument('-m', '--meaning',
                        action='store_true', default=True)
    parser.add_argument('-s', '--synonym',
                        action='store_true', default=True)
    parser.add_argument('-r', '--related', action='store_true')
    parser.add_argument('-e', '--example', action='store_true')
    parser.add_argument('--no-fmt', help='print definition without color')
    parser.add_argument('--less', help='view with pager(require less)')
    parser.add_argument('words', nargs='*')
    args = parser.parse_args()

    if args.words:
        if '--less' in sys.argv:
            os.system('python dict.py %s | less -r'% sys.argv[1])
        else:
            print_def(sys.argv[1])

    else :
        '''
        while True:
            try:
                print_def(raw_input('Enter word: \n'))
            except (EOFError, KeyboardInterrupt):
                print("Bye")
                exit(0)
        '''
        print(args.__dict__)

if __name__ == '__main__':
    main()
